### ISSUE TITLE
scan_al2s upgrade with new API

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/information-model-utils#80]
The OESS system is being decommissioned. AL2S AM need to work with its new Insight Console Virtual Network API.
* [x] Replace oess.py with al2s_api.py for the new Insight Console VN API @zlion 
* [x] Update arm.py as needed @xi-yang 
* [x] Replace scan_oess.py with scan_al2s.py with updated options as needed @xi-yang 

ETC: mid-November 2023

**Comment by zlion** [comment]
The arm.py and scan_al2s.py have been updated  but need netam.conf to run a full test.

**Comment by xi-yang** [comment]
> The arm.py and scan_al2s.py have been updated but need netam.conf to run a full test.

Good progress. Feel free to make necessary changes to the netam.conf and then update the README instructions. I will give  it a try when ready. 

Also feel free to clean up the old OESS related codes as we won't need OESS any more.

**Comment by zlion** [comment]
Removed OESS related stuff and updated the README. Please let me know if there is any question.

**Comment by zlion** [comment]
Issue: 
Missing "vlan_range" fields in the model file for some interfaces.

Reason:
The vlan_range string returned from scanner could be like “2-5, 7, 10-11”, which caused an internal exception when calling _update_vlan_label() because it failed the VALIDATOR rules. As a result, no vlan_range fields were output in the model file.

Solution:
Force the vlan_range string fit with the VALIDATOR rule for vlan_range, i.e. “2-5, 7-7, 10-11” to pass the validation.
